### ISSUE TITLE
Criação de novos eventos resulta em exceção de ValueError

### ISSUE THREAD

**Issue by dayvidallan** [plainspooky/django-agenda_de_eventos#2]
Bom dia, primeiro parabéns pela agenda bem fácil de usar, o que ocorre, quando vou cadastrar um novo evento e submeto aparece o seguinte erro:
[ValueError at _new.pdf](https://github.com/plainspooky/django-agenda_de_eventos/files/4972202/ValueError.at._new.pdf)

**Comment by plainspooky** [comment]
Realmente cometi um erro com a função `split_date()`, chamada em `events.views.new()`. Apesar da descrição informar que ela converte uma data em _string_ para criar a tupla de três elementos ela espera receber um objeto `datetime`:

``` python
def split_date(string_date, date_format="{:%Y-%m-%d}"):
    """
    Transforma a data em 'YYYY-MM-DD' em uma tupla de três valores para
    utilizar na visão de eventos de um determinado dia.
    """
    return tuple([int(i) for i in date_format.format(string_date)])
```
O que não acontecia em `new()` que já enviada a data como _string_ para a função, daí o erro.

Mas olhando o código eu vi que todas as chamadas para esta função eram meio confusas:

``` python
def delete(request, id:int):
    ...
    (year, month, day) = split_date("{:%Y-%m-%d}".format(event.date)
    ...
```

Preferi reescrevê-la para realmente fazer o que ela diz que faz (também deixei o nome mais sugestivo):

``` python
def split_str_date(date_as_string):
    """
    Transforma a data em 'YYYY-MM-DD' em uma tupla de três valores para
    utilizar na visão de eventos de um determinado dia.
    """
    year, month, day, *__ = date_as_string.split("-")
    return year, month, day
```
